backend:
  name: git-gateway
  branch: master

media_folder: "acontent/blog/{{slug}}"

collections:
- name: "blog"
  label: "Blog"
  folder: "content/blog/{{slug}}"
  create: true
  slug: "{{slug}}"
  fields:
    - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}